version: '2'
services:
  ayudokernel-app:
    image: ayudokernel
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ayudokernel-postgresql:5432/ayudoKernel
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8088:8088
  ayudokernel-postgresql:
    extends:
      file: postgresql.yml
      service: ayudokernel-postgresql
